"""
Project AEGIS - Security Risk Engine Models
Defines risk levels, privilege tiers, contextual inputs, factor contributions, and assessment outputs.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from services.common.models import FindingSeverity


class RiskLevel(StrEnum):
    """Calibrated four-tier risk classification for AEGIS decisioning."""

    LOW = "LOW"  # 0–25: Log telemetry, monitor baseline
    MEDIUM = "MEDIUM"  # 26–50: Generate SOC alert, update War Room
    HIGH = "HIGH"  # 51–75: Alert on-call, approval-gated containment
    CRITICAL = "CRITICAL"  # 76–100: Autonomous containment & isolation


class PrivilegeLevel(StrEnum):
    """Categorization of caller or compromised identity privilege."""

    UNPRIVILEGED = "UNPRIVILEGED"  # Basic read or non-sensitive service role (weight: 1.0)
    READ_ONLY = "READ_ONLY"  # Organization or cross-account reader (weight: 2.0)
    WORKLOAD_WRITE = "WORKLOAD_WRITE"  # Data plane write access on scoped resources (weight: 3.0)
    IAM_WRITE = "IAM_WRITE"  # Policy/role modification or STS minting (weight: 4.5)
    ADMINISTRATOR = "ADMINISTRATOR"  # Full cloud or account superuser permissions (weight: 5.0)


class ExposureLevel(StrEnum):
    """Network exposure and ingress boundary posture of the target asset."""

    ISOLATED_PRIVATE = "ISOLATED_PRIVATE"  # Private subnet with zero egress/ingress (weight: 1.0)
    INTERNAL_VPC = "INTERNAL_VPC"  # Standard internal VPC boundary (weight: 2.0)
    RESTRICTED_INGRESS = (
        "RESTRICTED_INGRESS"  # Ingress restricted by IP CIDR or SG peering (weight: 3.5)
    )
    INTERNET_FACING = (
        "INTERNET_FACING"  # Public IP, 0.0.0.0/0 ingress or public S3 bucket (weight: 5.0)
    )


class RiskFactorContribution(BaseModel):
    """Individual factor contributing to the aggregate explainable risk score."""

    model_config = ConfigDict(extra="forbid")

    factor_name: str = Field(description="Name of the evaluated risk factor")
    raw_value: float = Field(description="Input value before normalization")
    normalized_value: float = Field(
        ge=0.0,
        le=100.0,
        description="Value normalized to 0.0 - 100.0 scale",
    )
    weight: float = Field(
        ge=0.0,
        le=1.0,
        description="Assigned weighting coefficient",
    )
    weighted_contribution: float = Field(
        ge=0.0,
        le=100.0,
        description="Product of normalized value and weight",
    )
    narrative: str = Field(description="Human-readable justification for this factor")


class RiskContext(BaseModel):
    """Comprehensive contextual input payload evaluated by the Risk Engine."""

    model_config = ConfigDict(extra="forbid")

    finding_id: str = Field(description="Associated security finding ID")
    detection_severity: FindingSeverity = Field(
        default=FindingSeverity.MEDIUM,
        description="Severity assigned by detection engine or AWS native service",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence probability of the detection (0.0 to 1.0)",
    )
    asset_criticality: float = Field(
        default=1.0,
        ge=1.0,
        le=10.0,
        description="Business and operational criticality of target asset (1.0 to 10.0)",
    )
    privilege_level: PrivilegeLevel = Field(
        default=PrivilegeLevel.UNPRIVILEGED,
        description="Privilege tier of involved identity",
    )
    exposure_level: ExposureLevel = Field(
        default=ExposureLevel.INTERNAL_VPC,
        description="Ingress and network boundary exposure",
    )
    blast_radius_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Blast radius score (0.0 to 100.0) from Phase 08 Neptune graph analysis",
    )
    anomaly_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="SageMaker behavioral anomaly score (0.0 to 1.0) from Phase 07",
    )
    vulnerability_cvss: float | None = Field(
        default=None,
        ge=0.0,
        le=10.0,
        description="Optional Common Vulnerability Scoring System (CVSS v3) score",
    )
    is_production: bool = Field(
        default=False,
        description="Flag indicating if the target resides in a production environment",
    )
    cross_account: bool = Field(
        default=False,
        description="Flag indicating if finding or attack path traverses account boundaries",
    )


class RiskAssessment(BaseModel):
    """Complete, explainable risk score output generated by the AEGIS Risk Engine."""

    model_config = ConfigDict(extra="forbid")

    assessment_id: str = Field(description="Unique assessment identifier")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Timestamp of risk calculation",
    )
    finding_id: str = Field(description="Evaluated security finding ID")
    risk_score: float = Field(
        ge=0.0,
        le=100.0,
        description="Final deterministic risk score (0.0 to 100.0)",
    )
    risk_level: RiskLevel = Field(description="Categorical risk classification")
    recommended_action: str = Field(
        description="Prescribed response posture (e.g. log, alert, contain)",
    )
    factor_breakdown: list[RiskFactorContribution] = Field(
        description="Explicit breakdown of every scoring factor",
    )
    explanation: str = Field(
        description="Full human-readable synthesis of why this score was assigned",
    )
    raw_factors: dict[str, Any] = Field(
        default_factory=dict,
        description="Raw contextual parameters used in computation",
    )
